apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-rb
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: insights-rb
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - namespaces
      - endpoints
      - deployments
      - pods
      - jobs
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: insights-rb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: insights-rb
